#!/bin/sh

# Licensed under ISC by TFBC, published at
# https://github.com/thatfatblackcat/programs

# shellcheck disable=SC2015,SC2086
# SC2015: shellcheck complains for A && B || C --> pushsubs
# SC2086: shellcheck wants set -- $line quoted --> pushsubs


external() {
cat << __EOF__
<style>
/* Source from the stylesheet */
</style>
<script>
/* Source from the javascript */
</script>
__EOF__
}

pushsubs() {
case "$1" in
*.vtt) sed '/WEBVTT/,/^$/d;/STYLE/,/^$/d;/NOTE/,/^$/d;/-->/d' "$1" ;;
*.srt) tac "$1" | sed '/-->/,+1d' | tac ;;    *.txt|*.md) cat "$1" ;;
esac | while read -r buf0 || [ -n "$buf0$buf1$buf2$buf3$buf4$buf5$buf6" ]; do
	[ "$buf0" != "$buf1" ] && [ "$buf0" != "$buf2" ] &&
	[ "$buf0" != "$buf3" ] && [ "$buf0" != "$buf4" ] &&
	[ "$buf0" != "$buf5" ] && [ "$buf0" != "$buf6" ] || unset buf0
	line="$line $buf6"; buf6=$buf5; buf5=$buf4; buf4=$buf3
	                    buf3=$buf2; buf2=$buf1; buf1=$buf0
	[ -z "$buf6" ] && set -- $line && unset line && printf "%s\n\n" "$*"
done | sed '/^$/d;s/^/<p>/;s/$/<\/p>/'
}

template() {
cat > "${1%.*}.htm" << __EOF__
<!DOCTYPE html> <html> <head> <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>$TITLE $([ "$cnt" -lt 10 ] && echo "0$cnt" || echo "$cnt")</title>
$(external "$1") </head> <body>
<h1>$TITLE $([ "$cnt" -lt 10 ] && echo "0$cnt" || echo "$cnt")</h1>
$(pushsubs "$1") </body> </html>
__EOF__
}

for ext in txt md srt vtt; do cnt=0; for sub in *.$ext; do TITLE=$1
	[ ! -f "$sub" ] && continue || cnt=$((cnt + 1))
	dos2unix "$sub" && template "$sub"
done; done || (man "${0##*/}" && exit 1)
