.TH "1337X-WTF" "1" "January 2022" "ThatFatBlackCat" "TFBC"
.hy
.SH NAME
.PP
1337x-wtf — watch torrented movies without a subscription
.SH SYNOPSIS
.PP
\f[B]1337x-wtf\f[R] -- no arguments required
.SH DESCRIPTION
.PP
This script is a fork of notflix featuring actual comprehensible
shell code written by myself.
.SH LICENSING
.PP
Licensed under GPL by Bugswriter, published at
.PD 0
.P
.PD
https://github.com/Bugswriter/notflix
.PP
Since the original project is under a GPL license I'm
.PD 0
.P
.PD
legally oblied to honor it and keep it like that.
