.TH "4ANIME-DL" "1" "January 2022" "ThatFatBlackCat" "TFBC"
.hy
.SH NAME
.PP
4anime-dl — downloads anime from 4anime.to using youtube-dl
.SH SYNOPSIS
.PP
\f[B]4anime-dl\f[R] \f[I]TITLES\f[R]\&...
.SH EXPLANATION
.PP
Run the script specifying a list of anime to download.
.PD 0
.P
.PD
Currently unusable because 4anime.to closed their services.
.SH LICENSING
.PP
Licensed under ISC by TFBC, published at
.PD 0
.P
.PD
https://github.com/thatfatblackcat/programs
