.TH "MEKYO-FIX" "1" "January 2022" "ThatFatBlackCat" "TFBC"
.hy
.SH NAME
.PP
mekyo-fix — makes meikyou dictionary entries more readable
.SH SYNOPSIS
.PP
\f[B]mekyo-fix\f[R] [JSON ...]
.SH EXPLANATION
.PP
Run the script specifying JSON files to convert.
.PD 0
.P
.PD
If you find some bugs, open an issue on GitHub and I'll take care.
.SH LICENSING
.PP
Licensed under ISC by TFBC, published at
.PD 0
.P
.PD
https://github.com/thatfatblackcat/programs
