.TH "PUSH-SUBS" "1" "January 2022" "ThatFatBlackCat" "TFBC"
.hy
.SH NAME
.PP
push-subs — portable unified subtitles to html (PUSH)
.SH SYNOPSIS
.PP
\f[B]push-subs\f[R] \f[I]TITLE\f[R]
.SH DESCRIPTION
.PP
Transforms SRT and VTT into nicely formatted HTML documents that
.PD 0
.P
.PD
can be scripted or parsed by other apps like Yomichan.
.SH LICENSING
.PP
Licensed under ISC by TFBC, published at
.PD 0
.P
.PD
https://github.com/thatfatblackcat/programs
